platform :ios, '9.0'

target 'Todoey' do
  use_frameworks!

  # Pods for Todoey
  pod 'RealmSwift', '~> 5.4.3'
  pod 'SwipeCellKit'
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/wowansm/Chameleon.git', :branch => 'swift5'
end
